// export const BASE_URL="http://localhost:8000/api"
// export const BASE_URL="http://13.127.74.112/api/api"
export const BASE_URL="https://chargesol-backend.onrender.com/api"
// export const Base_url= "https://apis.samsarawellness.in/"
export const Base_url= "http://localhost:5000/"
// export const Base_url= "https://samsara-backend.onrender.com/"